name: "build_publish_deploy"

on:
   push:
      branches:
         - master

jobs:
   build_and_publish:
      name: "Build and Publish"
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v2
         - name: login to ghcr.io
           uses: docker/login-action@v2
           with:
              registry: ghcr.io
              username: DavidIlie
              password: ${{ secrets.GHCR_PASSWORD }}
         - name: build and push to container registry
           uses: docker/build-push-action@v3
           with:
              context: .
              push: true
              tags: ghcr.io/davidilie/vps-update-wireguard:latest
   deploy_self:
      name: "Deploy Self"
      runs-on: ubuntu-latest
      needs: [build_and_publish]
      steps:
         - name: "Set Kubernetes Context"
           uses: Azure/k8s-set-context@v1
           with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBE_CONFIG }}
         - name: "Restart deployment on DavidIlie's instance"
           run: kubectl rollout restart deploy vps-update-wireguard -n internal
