name: "build_publish_deploy"

on:
   push:
      branches:
         - master

permissions:
   contents: read
   packages: write

jobs:
   build_and_publish:
      name: "Build and Publish"
      runs-on: davidapps-linux-x64
      steps:
         - name: checkout
           uses: actions/checkout@v2
         - name: login to ghcr.io
           uses: docker/login-action@v2
           with:
              registry: ghcr.io
              username: DavidIlie
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: build and push to container registry
           uses: docker/build-push-action@v3
           with:
              context: .
              push: true
              cache-from: type=gha,scope=vps-update-wireguard
              cache-to: type=gha,mode=max,scope=vps-update-wireguard
              tags: ghcr.io/davidilie/vps-update-wireguard:latest
   deploy_self:
      name: "Deploy Self"
      runs-on: davidapps-linux-x64
      needs: [build_and_publish]
      steps:
         - name: "Set up kubectl"
           uses: azure/setup-kubectl@v4
         - name: "Set Kubernetes Context"
           uses: Azure/k8s-set-context@v1
           with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBE_CONFIG }}
         - name: "Restart deployment on DavidIlie's instance"
           run: kubectl rollout restart deploy vps-update-wireguard -n internal
